### ISSUE TITLE
Error when trying to save plotted map

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#41] opened 2020-06-24 13:17 UTC
**Describe the bug**
When saving a produced map after showing it, like in your example code:

```
from offspect.api import plot_map, CacheFile
# we load a cachefile
cf = CacheFile("example.hdf5")
# and plot and show it.
display = plot_map(cf)
display.show()
# you can also save the figure with
display.savefig("example_map.png")
```

the following error occurs:

```
Traceback (most recent call last):
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backend_bases.py", line 2785, in _wait_cursor_for_draw_cm
    self.set_cursor(cursors.WAIT)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backends\_backend_tk.py", line 544, in set_cursor
    window.configure(cursor=cursord[cursor])
  File "c:\users\bettina trunk\anaconda3\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "c:\users\bettina trunk\anaconda3\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name "."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 60, in <module>
    display.savefig(savepath+ "/" +patient + "/" +header+ ".png")
  File "C:\tool-offspect\.env\lib\site-packages\nilearn\plotting\displays.py", line 1044, in savefig
    edgecolor=edgecolor)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backend_bases.py", line 2105, in print_figure
    **kwargs)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backends\backend_agg.py", line 514, in print_png
    FigureCanvasAgg.draw(self)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backends\backend_agg.py", line 392, in draw
    else nullcontext()):
  File "c:\users\bettina trunk\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backend_bases.py", line 2788, in _wait_cursor_for_draw_cm
    self.set_cursor(self._lastCursor)
  File "C:\tool-offspect\.env\lib\site-packages\matplotlib\backends\_backend_tk.py", line 544, in set_cursor
    window.configure(cursor=cursord[cursor])
  File "c:\users\bettina trunk\anaconda3\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "c:\users\bettina trunk\anaconda3\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name "."
```

When not showing it beforehand (i.e. without display.show()), it is saved without any problems.

**Comment by agricolab** [comment] 2020-06-24 13:43
Does this error occur only in Spyder, or also when a script is run from the terminal?

**Comment by BettinaTrunk** [comment] 2020-06-24 13:46
This error occurs when the scrips is run from the terminal.

**Comment by agricolab** [comment] 2020-06-24 18:47
I can't recreate this error on my machine. It could be because your matplotlib is not using Qt5Agg as backend, see https://matplotlib.org/faq/usage_faq.html#what-is-a-backend With the following snippet can you check your current backend:
```
import matplotlib
matplotlib.get_backend()
```
This occurs in a running environment, doesn't it? Can you tell me the Python version you use and the installed packages?

**Comment by BettinaTrunk** [comment] 2020-06-25 08:36
My current backend is 'module://ipykernel.pylab.backend_inline'.

And yes, it occurs in a running environment for me. @FelixQuirm had this issue, too though, and as I can see from his screenshot, he is not using an environment. 
My Python version is 3.7 and I have the following packages installed:

Package         Version      Location
--------------- ------------ ----------------
cycler          0.10.0
h5py            2.10.0
joblib          0.14.1
kiwisolver      1.1.0
libeep          0.3
liesl           0.3.4.4
matplotlib      3.2.1
matprot         0.2
nibabel         3.0.2
nilearn         0.6.2
numpy           1.18.2
offspect        0.1.3        c:\tool-offspect
pip             20.0.2
pylsl           1.13.1
pyparsing       2.4.6
PyQt5           5.12.3
PyQt5-sip       12.7.1
python-dateutil 2.8.1
pyxdf           1.16.2
PyYAML          5.3.1
scikit-learn    0.22.2.post1
scipy           1.4.1
setuptools      46.0.0
six             1.14.0
sklearn         0.0
wheel           0.34.2

**Comment by agricolab** [comment] 2020-06-26 13:13
I can't reproduce the error, neither in Spyder with the TkAgg backend nor outside of it. It could be related to the filename? In the traceback, it says `display.savefig(savepath+ "/" +patient + "/" +header+ ".png")`?

**Comment by agricolab** [comment] 2020-06-26 13:13
Maybe we should meet remotely to see how this error occurs live, so we can work together at least.

**Comment by BettinaTrunk** [comment] 2020-06-26 13:20
I don't think it's related to the filename as it saves the map successfully without the display.show() beforehand and the error also occurs when I for example use display.savefig('example.png'). 

And sure, I would be happy to do that.

**Comment by agricolab** [comment] 2020-07-08 07:01
I tested this on the [Win 10 Developers VM](https://developer.microsoft.com/de-de/windows/downloads/virtual-machines/) with Anaconda Python 3.7.6 and could not reproduce the error. Yet, the default  matplotlib backend is Qt5Agg and matplotlib is 3.1.3. 

This is a very clean and fresh machine, but there are some slight differences to your environments. It starts to look like a anaconda issue?

**Comment by BettinaTrunk** [comment] 2020-07-09 06:40
That worked, thank you! After changing the backend to Qt5Agg, the error did not occur anymore.

**Comment by agricolab** [comment] 2020-07-09 07:54
Awesome! Closing the issue, then.

**Closed by agricolab** 2020-07-09 07:54 UTC
